global_costmap:
  global_frame: map
  robot_base_frame: base_footprint
  update_frequency: 5.0 
  publish_frequency: 2.0
  #always_send_full_costmap: false #default is false
  rolling_window: false
  resolution: 0.05 
  width: 30 # 60 # For 3b point we modified the width at 60 value  
  height: 30 # 60 # For 3b point we modified the height at 60 value  
  origin_x: -15 
  origin_y: -15 
